import type { Metadata } from "next";
import { Inter, Bodoni_Moda } from "next/font/google";
import "./globals.css";
import { EnquiryProvider } from "@/components/EnquiryProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const bodoni = Bodoni_Moda({
  subsets: ["latin"],
  variable: "--font-bodoni",
  display: "swap",
});

export const metadata: Metadata = {
  /* =========================================================
     BASIC SEO
  ========================================================= */

  metadataBase: new URL("https://www.ethiopiamaps.com"),

  title: {
    default: "Ethiopia Maps | Contemporary Ethiopian Art",
    template: "%s | Ethiopia Maps",
  },

  description:
    "Discover contemporary Ethiopian art, photography, and fine art prints inspired by the landscapes, cities, and culture of Ethiopia.",
keywords: [
  "Ethiopia Maps",
  "EthiopiaMaps",
  "Ethiopian Maps",
  "Ethiopian map",
  "Ethiopia map",
  "Map of Ethiopia",
  "Maps of Ethiopia",
  "Ethiopian city maps",
  "Ethiopian city map",
  "Maps of Ethiopian cities",
  "Ethiopian cities",
  "Cities of Ethiopia",
  "Ethiopian urban maps",
  "Ethiopian cartography",
  "Ethiopian map art",
  "Ethiopia map art",
  "Ethiopian map artwork",
  "Ethiopia map artwork",
  "Ethiopian map print",
  "Ethiopian map prints",
  "Ethiopia map print",
  "Ethiopian map poster",
  "Ethiopian map posters",
  "Ethiopian map wall art",
  "Ethiopian map wall decor",
  "Ethiopian city map art",
  "Ethiopian city map artwork",
  "Ethiopian city map print",
  "Ethiopian city map prints",
  "Ethiopian city map poster",
  "Ethiopian city map wall art",
  "Ethiopian art",
  "Ethiopian artwork",
  "Ethiopian art prints",
  "Ethiopian fine art",
  "Ethiopian fine art prints",
  "Ethiopian contemporary art",
  "Contemporary Ethiopian art",
  "Ethiopian contemporary artwork",
  "Ethiopian artists",
  "Ethiopian visual art",
  "Ethiopian visual culture",
  "Ethiopian design",
  "Ethiopian graphic design",
  "Ethiopian graphic art",
  "Ethiopian photography",
  "Ethiopian photography prints",
  "Ethiopian architecture",
  "Ethiopian architectural art",
  "Ethiopian architectural artwork",
  "Ethiopian cultural art",
  "Ethiopian cultural artwork",
  "Ethiopian heritage art",
  "Ethiopian wall art",
  "Ethiopian wall decor",
  "Ethiopian wall prints",
  "Ethiopian framed prints",
  "Ethiopian canvas prints",
  "Ethiopian posters",
  "Ethiopian art posters",
  "Ethiopian prints",
  "Ethiopian art for home",
  "Ethiopian artwork for home",
  "Ethiopian art for walls",
  "Ethiopian home decor",
  "Ethiopian interior art",
  "Ethiopian interior decor",
  "Ethiopian travel art",
  "Ethiopian travel posters",
  "Ethiopian travel prints",
  "Ethiopian landscape art",
  "Ethiopian urban art",
  "Ethiopian urban design",
  "Ethiopian city architecture",
  "Ethiopian urban landscape",
  "Ethiopian urban identity",
  "Addis Ababa",
  "Addis Ababa Ethiopia",
  "Addis Ababa map",
  "Addis Ababa city map",
  "Addis Ababa map art",
  "Addis Ababa map artwork",
  "Addis Ababa map print",
  "Addis Ababa map poster",
  "Addis Ababa map wall art",
  "Addis Ababa wall art",
  "Addis Ababa wall decor",
  "Addis Ababa art",
  "Addis Ababa artwork",
  "Addis Ababa art print",
  "Addis Ababa prints",
  "Addis Ababa poster",
  "Addis Ababa city art",
  "Addis Ababa city artwork",
  "Addis Ababa street map",
  "Addis Ababa urban art",
  "Addis Ababa architecture",
  "Addis Ababa architectural art",
  "Bahir Dar",
  "Bahir Dar Ethiopia",
  "Bahir Dar map",
  "Bahir Dar city map",
  "Bahir Dar map art",
  "Bahir Dar map artwork",
  "Bahir Dar map print",
  "Bahir Dar map poster",
  "Bahir Dar wall art",
  "Bahir Dar artwork",
  "Gondar",
  "Gonder",
  "Gondar Ethiopia",
  "Gondar map",
  "Gonder map",
  "Gondar city map",
  "Gondar map art",
  "Gondar map artwork",
  "Gondar map print",
  "Gondar wall art",
  "Gondar artwork",
  "Dire Dawa",
  "Dire Dawa Ethiopia",
  "Dire Dawa map",
  "Dire Dawa city map",
  "Dire Dawa map art",
  "Dire Dawa map artwork",
  "Dire Dawa map print",
  "Dire Dawa map poster",
  "Dire Dawa wall art",
  "Dire Dawa artwork",
  "Mekelle",
  "Mekele",
  "Mekelle Ethiopia",
  "Mekele Ethiopia",
  "Mekelle map",
  "Mekele map",
  "Mekelle city map",
  "Mekele city map",
  "Mekelle map art",
  "Mekele map art",
  "Mekelle map print",
  "Mekele map print",
  "Mekelle wall art",
  "Mekelle artwork",
  "Hawassa",
  "Awassa",
  "Hawassa Ethiopia",
  "Hawassa map",
  "Awassa map",
  "Hawassa city map",
  "Hawassa map art",
  "Hawassa map artwork",
  "Hawassa map print",
  "Hawassa wall art",
  "Hawassa artwork",
  "Jimma",
  "Jimma Ethiopia",
  "Jimma map",
  "Jimma city map",
  "Jimma map art",
  "Jimma map artwork",
  "Jimma map print",
  "Jimma map poster",
  "Jimma wall art",
  "Jimma artwork",
  "Harar",
  "Harar Ethiopia",
  "Harar map",
  "Harar city map",
  "Harar map art",
  "Harar map artwork",
  "Harar map print",
  "Harar map poster",
  "Harar wall art",
  "Harar artwork",
  "Harari art",
  "Adama",
  "Adama Ethiopia",
  "Nazret",
  "Nazret Ethiopia",
  "Adama map",
  "Nazret map",
  "Adama city map",
  "Adama map art",
  "Adama map artwork",
  "Adama map print",
  "Adama map poster",
  "Adama wall art",
  "Dessie",
  "Dessie Ethiopia",
  "Dessie map",
  "Dessie city map",
  "Dessie map art",
  "Dessie map artwork",
  "Dessie map print",
  "Dessie wall art",
  "Dessie artwork",
  "Jijiga",
  "Jijiga Ethiopia",
  "Jijiga map",
  "Jijiga city map",
  "Jijiga map art",
  "Jijiga map artwork",
  "Jijiga map print",
  "Jijiga wall art",
  "Jijiga artwork",
  "Bishoftu",
  "Bishoftu Ethiopia",
  "Debre Zeit",
  "Debre Zeyit",
  "Bishoftu map",
  "Debre Zeit map",
  "Debre Zeyit map",
  "Bishoftu city map",
  "Bishoftu map art",
  "Bishoftu map artwork",
  "Bishoftu map print",
  "Bishoftu wall art",
  "Shashamane",
  "Shashemene",
  "Shashamane Ethiopia",
  "Shashemene Ethiopia",
  "Shashamane map",
  "Shashemene map",
  "Shashamane city map",
  "Shashemene city map",
  "Shashamane map art",
  "Shashemene map art",
  "Shashamane map print",
  "Shashemene map print",
  "Shashamane wall art",
  "Arba Minch",
  "Arbaminch",
  "Arba Minch Ethiopia",
  "Arba Minch map",
  "Arbaminch map",
  "Arba Minch city map",
  "Arba Minch map art",
  "Arba Minch map artwork",
  "Arba Minch map print",
  "Arba Minch wall art",
  "Ambo",
  "Ambo Ethiopia",
  "Ambo map",
  "Ambo city map",
  "Ambo map art",
  "Ambo map artwork",
  "Ambo map print",
  "Ambo wall art",
  "Ambo artwork",
  "Debre Birhan",
  "Debre Birhan Ethiopia",
  "Debre Birhan map",
  "Debre Birhan city map",
  "Debre Birhan map art",
  "Debre Birhan map print",
  "Nekemte",
  "Nekemte Ethiopia",
  "Nekemte map",
  "Nekemte city map",
  "Nekemte map art",
  "Nekemte map print",
  "Kombolcha",
  "Kombolcha Ethiopia",
  "Kombolcha map",
  "Kombolcha city map",
  "Kombolcha map art",
  "Kombolcha map print",
  "Lalibela",
  "Lalibela Ethiopia",
  "Lalibela map",
  "Lalibela city map",
  "Lalibela map art",
  "Lalibela map artwork",
  "Lalibela map print",
  "Lalibela wall art",
  "Lalibela artwork",
  "Axum",
  "Aksum",
  "Axum Ethiopia",
  "Aksum Ethiopia",
  "Axum map",
  "Aksum map",
  "Axum city map",
  "Aksum city map",
  "Axum map art",
  "Aksum map art",
  "Axum map artwork",
  "Aksum map artwork",
  "Axum map print",
  "Aksum map print",
  "Axum wall art",
  "Aksum wall art",
  "Adwa",
  "Adwa Ethiopia",
  "Adwa map",
  "Adwa city map",
  "Adwa map art",
  "Adwa map print",
  "Adwa wall art",
  "Adigrat",
  "Adigrat Ethiopia",
  "Adigrat map",
  "Adigrat city map",
  "Adigrat map art",
  "Adigrat map print",
  "Shire",
  "Shire Ethiopia",
  "Shire map",
  "Shire city map",
  "Shire map art",
  "Debre Markos",
  "Debre Markos Ethiopia",
  "Debre Markos map",
  "Debre Markos city map",
  "Debre Markos map art",
  "Debre Markos map print",
  "Debre Tabor",
  "Debre Tabor Ethiopia",
  "Debre Tabor map",
  "Debre Tabor city map",
  "Debre Tabor map art",
  "Debre Tabor map print",
  "Ziway",
  "Ziway Ethiopia",
  "Zeway",
  "Ziway map",
  "Zeway map",
  "Ziway city map",
  "Ziway map art",
  "Ziway map print",
  "Jinka",
  "Jinka Ethiopia",
  "Jinka map",
  "Jinka city map",
  "Jinka map art",
  "Jinka map print",
  "Asosa",
  "Assosa",
  "Asosa Ethiopia",
  "Assosa Ethiopia",
  "Asosa map",
  "Assosa map",
  "Asosa city map",
  "Asosa map art",
  "Asosa map print",
  "Gambela",
  "Gambella",
  "Gambela Ethiopia",
  "Gambella Ethiopia",
  "Gambela map",
  "Gambella map",
  "Gambela city map",
  "Gambela map art",
  "Gambella map art",
  "Semera",
  "Semera Ethiopia",
  "Semera map",
  "Semera city map",
  "Semera map art",
  "Wolaita Sodo",
  "Wolaita Sodo Ethiopia",
  "Sodo Ethiopia",
  "Wolaita Sodo map",
  "Sodo map",
  "Wolaita Sodo city map",
  "Wolaita Sodo map art",
  "Dilla",
  "Dilla Ethiopia",
  "Dilla map",
  "Dilla city map",
  "Dilla map art",
  "Dilla map print",
  "Hosaena",
  "Hosaena Ethiopia",
  "Hosaena map",
  "Hosaena city map",
  "Mizan Teferi",
  "Mizan Teferi Ethiopia",
  "Mizan Teferi map",
  "Mizan Teferi city map",
  "Woldiya",
  "Woldiya Ethiopia",
  "Woldiya map",
  "Woldiya city map",
  "Bonga",
  "Bonga Ethiopia",
  "Bonga map",
  "Bonga city map",
  "African art",
  "African artwork",
  "African art prints",
  "African fine art",
  "African fine art prints",
  "African contemporary art",
  "Contemporary African art",
  "African contemporary artwork",
  "African artists",
  "African visual art",
  "African visual culture",
  "African photography",
  "African photography prints",
  "African design",
  "African graphic design",
  "African graphic art",
  "African architecture",
  "African architectural art",
  "African architectural artwork",
  "African cultural art",
  "African cultural artwork",
  "African heritage art",
  "African heritage artwork",
  "African wall art",
  "African wall decor",
  "African wall prints",
  "African framed prints",
  "African canvas prints",
  "African posters",
  "African art posters",
  "African prints",
  "African art for home",
  "African artwork for home",
  "African art for walls",
  "African home decor",
  "African interior art",
  "African interior decor",
  "African travel art",
  "African travel posters",
  "African travel prints",
  "African landscape art",
  "African urban art",
  "African urban design",
  "African urban landscape",
  "African urban identity",
  "African city architecture",
  "African city design",
  "African contemporary design",
  "Africa map",
  "Map of Africa",
  "African map",
  "African maps",
  "Africa map art",
  "African map art",
  "African map artwork",
  "African map print",
  "African map prints",
  "Africa map print",
  "African map poster",
  "Africa map poster",
  "African map wall art",
  "Africa map wall art",
  "African city maps",
  "African city map",
  "Maps of African cities",
  "Map of African cities",
  "African city map art",
  "African city map artwork",
  "African city map print",
  "African city map prints",
  "African city map posters",
  "African city map wall art",
  "African city artwork",
  "African city art",
  "African city prints",
  "African city posters",
  "African city wall art",
  "African city wall decor",
  "African cities",
  "Cities of Africa",
  "African capitals",
  "African capital cities",
  "African cartography",
  "African mapping",
  "African urban maps",
  "African urban artwork",
  "East Africa",
  "East African art",
  "East African artwork",
  "East African art prints",
  "East African maps",
  "East African map art",
  "East African city maps",
  "East African cities",
  "East African city art",
  "East African wall art",
  "East African design",
  "East African architecture",
  "Horn of Africa",
  "Horn of Africa art",
  "Horn of Africa artwork",
  "Horn of Africa maps",
  "Horn of Africa map art",
  "Horn of Africa city maps",
  "Horn of Africa cities",
  "Horn of Africa wall art",
  "Horn of Africa design",
  "Horn of Africa architecture",
  "Nile cities",
  "Cities of the Nile",
  "Nile map",
  "Nile map art",
  "Nile map print",
  "Nile city maps",
  "Nile cities map",
  "Blue Nile",
  "Blue Nile map",
  "Blue Nile art",
  "White Nile",
  "White Nile map",
  "White Nile art",
  "Jinja",
  "Jinja Uganda",
  "Jinja map",
  "Jinja city map",
  "Jinja map art",
  "Jinja map print",
  "Khartoum",
  "Khartoum Sudan",
  "Khartoum map",
  "Khartoum city map",
  "Khartoum map art",
  "Khartoum map artwork",
  "Khartoum map print",
  "Khartoum wall art",
  "Juba",
  "Juba South Sudan",
  "Juba map",
  "Juba city map",
  "Juba map art",
  "Juba map print",
  "Asmara",
  "Asmara Eritrea",
  "Asmara map",
  "Asmara city map",
  "Asmara map art",
  "Asmara map print",
  "Asmara wall art",
  "Massawa",
  "Massawa Eritrea",
  "Massawa map",
  "Massawa city map",
  "Massawa map art",
  "Djibouti",
  "Djibouti City",
  "Djibouti City map",
  "Djibouti map",
  "Djibouti city map",
  "Djibouti map art",
  "Djibouti map print",
  "Mogadishu",
  "Mogadishu Somalia",
  "Mogadishu map",
  "Mogadishu city map",
  "Mogadishu map art",
  "Mogadishu map print",
  "Nairobi",
  "Nairobi Kenya",
  "Nairobi map",
  "Nairobi city map",
  "Nairobi map art",
  "Nairobi map print",
  "Nairobi wall art",
  "Nairobi artwork",
  "Mombasa",
  "Mombasa Kenya",
  "Mombasa map",
  "Mombasa city map",
  "Mombasa map art",
  "Mombasa map print",
  "Kampala",
  "Kampala Uganda",
  "Kampala map",
  "Kampala city map",
  "Kampala map art",
  "Kampala map print",
  "Entebbe",
  "Entebbe Uganda",
  "Entebbe map",
  "Entebbe city map",
  "Kigali",
  "Kigali Rwanda",
  "Kigali map",
  "Kigali city map",
  "Kigali map art",
  "Kigali map print",
  "Kigali wall art",
  "Dar es Salaam",
  "Dar es Salaam Tanzania",
  "Dar es Salaam map",
  "Dar es Salaam city map",
  "Dar es Salaam map art",
  "Dar es Salaam map print",
  "Zanzibar",
  "Zanzibar Tanzania",
  "Zanzibar map",
  "Zanzibar city map",
  "Zanzibar map art",
  "Zanzibar wall art",
  "Stone Town",
  "Stone Town Zanzibar",
  "Stone Town map",
  "Stone Town city map",
  "Stone Town map art",
  "Arusha",
  "Arusha Tanzania",
  "Arusha map",
  "Arusha city map",
  "Arusha map art",
  "Cairo",
  "Cairo Egypt",
  "Cairo map",
  "Cairo city map",
  "Cairo map art",
  "Cairo map artwork",
  "Cairo map print",
  "Cairo wall art",
  "Cairo artwork",
  "Alexandria",
  "Alexandria Egypt",
  "Alexandria map",
  "Alexandria city map",
  "Alexandria map art",
  "Alexandria map print",
  "Luxor",
  "Luxor Egypt",
  "Luxor map",
  "Luxor city map",
  "Luxor map art",
  "Luxor map print",
  "Aswan",
  "Aswan Egypt",
  "Aswan map",
  "Aswan city map",
  "Aswan map art",
  "Aswan map print",
  "Rosetta",
  "Rosetta Egypt",
  "Rosetta map",
  "Rosetta city map",
  "Rosetta map art",
  "Tripoli",
  "Tripoli Libya",
  "Tripoli map",
  "Tripoli city map",
  "Tunis",
  "Tunis Tunisia",
  "Tunis map",
  "Tunis city map",
  "Tunis map art",
  "Algiers",
  "Algiers Algeria",
  "Algiers map",
  "Algiers city map",
  "Algiers map art",
  "Casablanca",
  "Casablanca Morocco",
  "Casablanca map",
  "Casablanca city map",
  "Casablanca map art",
  "Marrakech",
  "Marrakech Morocco",
  "Marrakech map",
  "Marrakech city map",
  "Marrakech map art",
  "Rabat",
  "Rabat Morocco",
  "Rabat map",
  "Rabat city map",
  "Rabat map art",
  "Lagos",
  "Lagos Nigeria",
  "Lagos map",
  "Lagos city map",
  "Lagos map art",
  "Lagos map print",
  "Lagos wall art",
  "Abuja",
  "Abuja Nigeria",
  "Abuja map",
  "Abuja city map",
  "Abuja map art",
  "Abuja map print",
  "Ibadan",
  "Ibadan Nigeria",
  "Ibadan map",
  "Ibadan city map",
  "Ibadan map art",
  "Accra",
  "Accra Ghana",
  "Accra map",
  "Accra city map",
  "Accra map art",
  "Accra map print",
  "Accra wall art",
  "Kumasi",
  "Kumasi Ghana",
  "Kumasi map",
  "Kumasi city map",
  "Kumasi map art",
  "Kumasi map print",
  "Dakar",
  "Dakar Senegal",
  "Dakar map",
  "Dakar city map",
  "Dakar map art",
  "Dakar map print",
  "Abidjan",
  "Abidjan Ivory Coast",
  "Abidjan Côte d'Ivoire",
  "Abidjan map",
  "Abidjan city map",
  "Abidjan map art",
  "Abidjan map print",
  "Freetown",
  "Freetown Sierra Leone",
  "Freetown map",
  "Freetown city map",
  "Freetown map art",
  "Monrovia",
  "Monrovia Liberia",
  "Monrovia map",
  "Monrovia city map",
  "Monrovia map art",
  "Conakry",
  "Conakry Guinea",
  "Conakry map",
  "Conakry city map",
  "Conakry map art",
  "Bamako",
  "Bamako Mali",
  "Bamako map",
  "Bamako city map",
  "Bamako map art",
  "Ouagadougou",
  "Ouagadougou Burkina Faso",
  "Ouagadougou map",
  "Ouagadougou city map",
  "Ouagadougou map art",
  "Niamey",
  "Niamey Niger",
  "Niamey map",
  "Niamey city map",
  "Niamey map art",
  "Lome",
  "Lomé",
  "Lome Togo",
  "Lomé Togo",
  "Lome map",
  "Lomé map",
  "Lome city map",
  "Lomé city map",
  "Lome map art",
  "Lomé map art",
  "Cotonou",
  "Cotonou Benin",
  "Cotonou map",
  "Cotonou city map",
  "Cotonou map art",
  "Kinshasa",
  "Kinshasa DRC",
  "Kinshasa Democratic Republic of Congo",
  "Kinshasa map",
  "Kinshasa city map",
  "Kinshasa map art",
  "Kinshasa map print",
  "Lubumbashi",
  "Lubumbashi DRC",
  "Lubumbashi map",
  "Brazzaville",
  "Brazzaville Congo",
  "Brazzaville map",
  "Brazzaville city map",
  "Brazzaville map art",
  "Luanda",
  "Luanda Angola",
  "Luanda map",
  "Luanda city map",
  "Luanda map art",
  "Luanda map print",
  "Windhoek",
  "Windhoek Namibia",
  "Windhoek map",
  "Windhoek city map",
  "Windhoek map art",
  "Gaborone",
  "Gaborone Botswana",
  "Gaborone map",
  "Gaborone city map",
  "Gaborone map art",
  "Harare",
  "Harare Zimbabwe",
  "Harare map",
  "Harare city map",
  "Harare map art",
  "Harare map print",
  "Bulawayo",
  "Bulawayo Zimbabwe",
  "Bulawayo map",
  "Bulawayo city map",
  "Lusaka",
  "Lusaka Zambia",
  "Lusaka map",
  "Lusaka city map",
  "Lusaka map art",
  "Lusaka map print",
  "Maputo",
  "Maputo Mozambique",
  "Maputo map",
  "Maputo city map",
  "Maputo map art",
  "Maputo map print",
  "Johannesburg",
  "Johannesburg South Africa",
  "Johannesburg map",
  "Johannesburg city map",
  "Johannesburg map art",
  "Johannesburg map print",
  "Johannesburg wall art",
  "Cape Town",
  "Cape Town South Africa",
  "Cape Town map",
  "Cape Town city map",
  "Cape Town map art",
  "Cape Town map print",
  "Cape Town wall art",
  "Durban",
  "Durban South Africa",
  "Durban map",
  "Durban city map",
  "Durban map art",
  "Pretoria",
  "Pretoria South Africa",
  "Pretoria map",
  "Pretoria city map",
  "Pretoria map art",
  "Gqeberha",
  "Gqeberha South Africa",
  "Gqeberha map",
  "Gqeberha city map",
  "Gqeberha map art",
  "Port Elizabeth",
  "Port Elizabeth South Africa",
  "Port Elizabeth map",
  "Port Elizabeth city map",
  "Antananarivo",
  "Antananarivo Madagascar",
  "Antananarivo map",
  "Antananarivo city map",
  "Antananarivo map art",
  "Port Louis",
  "Port Louis Mauritius",
  "Port Louis map",
  "Port Louis city map",
  "Port Louis map art",
  "Victoria Seychelles",
  "Victoria Seychelles map",
  "Victoria Seychelles city map",
  "Victoria Seychelles map art",
  "city map",
  "city maps",
  "city map art",
  "city map artwork",
  "city map print",
  "city map prints",
  "city map poster",
  "city map posters",
  "city map wall art",
  "city map wall decor",
  "map art",
  "map artwork",
  "map print",
  "map prints",
  "map poster",
  "map posters",
  "map wall art",
  "map wall decor",
  "wall map",
  "wall map art",
  "decorative maps",
  "decorative map art",
  "illustrated maps",
  "illustrated map art",
  "artistic maps",
  "modern maps",
  "modern map art",
  "contemporary maps",
  "contemporary map art",
  "urban map art",
  "urban maps",
  "city artwork",
  "city art",
  "city prints",
  "city posters",
  "city wall art",
  "city wall decor",
  "framed map",
  "framed map art",
  "framed map print",
  "fine art map",
  "fine art maps",
  "map decor",
  "map home decor",
  "map artwork for wall",
  "city artwork for wall",
  "cartographic art",
  "cartographic artwork",
  "contemporary cartography",
  "artistic cartography",
  "urban cartography",
  "city cartography",
  "map illustration",
  "map illustrations",
  "illustrated city maps",
  "illustrated African maps",
  "illustrated Ethiopian maps",
  "African architecture",
  "African architectural art",
  "African architectural artwork",
  "African urban design",
  "African city architecture",
  "African city design",
  "African urban landscape",
  "African urban identity",
  "African contemporary design",
  "African graphic design",
  "African visual culture",
  "African cultural artwork",
  "African heritage artwork",
  "African travel art",
  "African travel posters",
  "African travel prints",
  "African landscape art",
  "Ethiopian architecture",
  "Ethiopian architectural art",
  "Ethiopian architectural artwork",
  "Ethiopian urban design",
  "Ethiopian city architecture",
  "Ethiopian urban landscape",
  "Ethiopian urban identity",
  "Ethiopian contemporary design",
  "Ethiopian graphic design",
  "Ethiopian visual culture",
  "Ethiopian cultural artwork",
  "Ethiopian heritage artwork",
  "Ethiopian travel art",
  "Ethiopian travel posters",
  "Ethiopian travel prints",
],

  authors: [
    {
      name: "Ethiopia Maps",
    },
  ],

  creator: "Ethiopia Maps",
  publisher: "Ethiopia Maps",

  /* =========================================================
     CANONICAL / ROBOTS
  ========================================================= */

  alternates: {
    canonical: "/",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },

  /* =========================================================
     FAVICON / ICONS
  ========================================================= */

  icons: {
    icon: [
      {
        url: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        url: "/4.webp",
        type: "image/webp",
      },
    ],

    apple: [
      {
        url: "/addis.png",
        type: "image/png",
      },
    ],
  },

  /* =========================================================
     OPEN GRAPH
     
     Used when sharing the website on:
     - Facebook
     - WhatsApp
     - LinkedIn
     - Discord
     - etc.
     
     Put your social sharing image here:
     
     /public/images/og-image.jpg
  ========================================================= */

  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://www.ethiopiamaps.com",

    siteName: "Ethiopia Maps",

    title: "Ethiopia Maps | Contemporary Ethiopian Art",

    description:
      "Discover contemporary Ethiopian art, photography, and fine art prints inspired by the landscapes, cities, and culture of Ethiopia.",

    images: [
      {
        url: "/images/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Ethiopia Maps — Contemporary Ethiopian Art",
      },
    ],
  },

  /* =========================================================
     TWITTER / X
  ========================================================= */

  twitter: {
    card: "summary_large_image",

    title: "Ethiopia Maps | Contemporary Ethiopian Art",

    description:
      "Discover contemporary Ethiopian art, photography, and fine art prints inspired by Ethiopia.",

    images: ["/images/og-image.jpg"],
  },

  /* =========================================================
     OTHER METADATA
  ========================================================= */

  category: "Art & Photography",

  formatDetection: {
    telephone: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${bodoni.variable}`}
      >
        <EnquiryProvider>
          {children}
        </EnquiryProvider>
      </body>
    </html>
  );
}